databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './src/backend/build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --chdir src/backend' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString