# Generated by Django 5.2.1 on 2025-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_add_social_media_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ORCID IDs que este usuário está seguindo.'),
        ),
    ]
